# mention the port of your microservice
server:
  port: 9092
# you don't need to mention to register with eureka 
# you need to see the cicuit breaker states through actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      getMessage:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50s
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - com.netflix.client.ClientException
          - feign.RetryableException
          
 
